# [[language]]
# name = "scheme"
# formatter = { command = "raco", args = ["fmt", "-i"] }
# auto-format = true
# language-servers = [ "steel-language-server" ]

# For development
# [language-server.steel-language-server]
# command = "steel-language-server"
# args = []


# [language-server.rust-analyzer.config]
# experimental = { testExplorer = true }

# [[language]]
# name = "java"
# file-types = ["java", "jav", "pde"]
